name: iOS

on:
  release:
    types: [published]
  push:
    branches: [ iOS ]
  pull_request:
    branches: [ iOS ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - run: brew install openssl zmq
    - run: sh ./downloadAndCompile.sh
      env:
        EXTRA_CONFIGURE_FLAGS_OSX: -with-openssl=/usr/local/Cellar/openssl@1.1/1.1.1k/
    - run: ls -lR > ls.log
    - uses: actions/upload-artifact@v2
      with:
        name: logs
        path: |
          *.log
