name: iOS

on:
  release:
    types: [edited]
#   push:
#     branches: [ master ]
#   pull_request:
#     branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: sh ./downloadAndCompile.sh
    - run: ls -lR > ls.log
    - uses: actions/upload-artifact@v2
      with:
        name: logs
        path: |
          *.log
